#!/bin/bash
# Matt Layher, 4/6/13
# Simple shell script which a new apache virtualhost

# environment
TMPFILE="/tmp/mkvhost"
HTTPDCONF="/etc/apache2/conf.d/httpd.conf"
HTTPROOT="/var/www/"
HTTPLOG="/var/log/apache2/"
HTTPUSER="www-data"

# check for argument
if [ -n "$1" ] ; then
	# create directory
	sudo mkdir $HTTPROOT$1
	sudo chown $HTTPUSER:$HTTPUSER $HTTPROOT$1

	# create log directory
	sudo mkdir $HTTPLOG$1

	# generate vhost configuration
	echo "# mkvhost $1" > $TMPFILE
	echo "<VirtualHost *:80>" >> $TMPFILE
	echo -e "\tDocumentRoot $HTTPROOT$1" >> $TMPFILE
	echo -e "\tServerName $1" >> $TMPFILE
	echo -e "\tCustomLog $HTTPLOG$1/access.log \"common\"" >> $TMPFILE
	echo -e "\tErrorLog $HTTPLOG$1/error.log" >> $TMPFILE
	echo -e "</VirtualHost>\n" >> $TMPFILE

	# apply vhost configuration
	sudo cat $TMPFILE >> $HTTPDCONF

	# remove tmpfile
	rm $TMPFILE

	# restart apache
	sudo /etc/init.d/apache2 restart

	# done!
	echo "$0: created vhost $1, done."
else
	echo "usage: $0 [host]"
fi
